### ISSUE TITLE
Tab expansion hasn't changed after installation

### ISSUE THREAD

**Issue by wfendler** [Yatoom/emmet-atom-simplified#4]
I installed this and shift+space doesn't work but tab still does. I've uninstalled the normal Emmet and restarted Atom a few times.

On top of still using the old behavior my Craft Twig expansion is still broken as well.
https://github.com/fruitstudios/Craft-Twig/issues/4

Any ideas? Is Atom somehow stuck on my old version of Emmet?

**Comment by Yatoom** [comment]
Hi, is this still an issue?
